apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dy3d1v980-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dy3d1v980-nodejs 
  name: dy3d1v980-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dy3d1v980-nodejs 
